: Delete all extraneous LaTeX files (from .gitignore) in all subdirectories (not .pdf)

del /s _minted*
del /s .*.lb
del /s .*.swp
del /s ./auto/*
del /s .pdf
del /s .texpadtmp
del /s *-blx.aux
del /s *-blx.bib
del /s *-concordance.tex
del /s *-converted-to.*
del /s *-gnuplottex-*
del /s *-tags.tex
del /s *-tikzDictionary
del /s *.?end
:del /s *.[1-9]
:del /s *.[1-9][0-9]
:del /s *.[1-9][0-9][0-9]
:del /s *.[1-9][0-9][0-9]R
:del /s *.[1-9][0-9]R
:del /s *.[1-9]R
del /s *.4ct
del /s *.4tc
del /s *.acn
del /s *.acr
del /s *.alg
del /s *.aux
del /s *.auxlock
del /s *.backup
del /s *.bak
del /s *.bbl
del /s *.bcf
del /s *.blg
del /s *.brf
del /s *.cb
del /s *.cb2
del /s *.cpt
del /s *.cut
del /s *.dpth
del /s *.dvi
del /s *.el
:del /s *.eledsec[1-9]
:del /s *.eledsec[1-9][0-9]
:del /s *.eledsec[1-9][0-9][0-9]
:del /s *.eledsec[1-9][0-9][0-9]R
:del /s *.eledsec[1-9][0-9]R
:del /s *.eledsec[1-9]R
del /s *.end
del /s *.ent
del /s *.fdb_latexmk
del /s *.fff
del /s *.fls
del /s *.fmt
del /s *.fot
del /s *.gaux
del /s *.glg
del /s *.glo
del /s *.glog
del /s *.gls
del /s *.glsdefs
del /s *.glstex
del /s *.gnuplot
del /s *.gtex
del /s *.hst
del /s *.idv
del /s *.idx
del /s *.ilg
del /s *.ind
del /s *.lg
del /s *.listing
del /s *.loa
del /s *.lod
del /s *.loe
del /s *.lof
del /s *.log
del /s *.lol
del /s *.lot
del /s *.lox
del /s *.lpz
del /s *.ltjruby
del /s *.lyx~
del /s *.lzo
del /s *.lzs
del /s *.maf
del /s *.md5
del /s *.mf
del /s *.mlf
del /s *.mlt
del /s *.mp
:del /s *.mtc[0-9]*
del /s *.mw
del /s *.nav
del /s *.newpax
del /s *.nlg
del /s *.nlo
del /s *.nls
del /s *.out
del /s *.pax
del /s *.pdfpc
del /s *.pdfsync
del /s *.pre
del /s *.ptc
del /s *.pyg
del /s *.pytxcode
del /s *.run.xml
del /s *.sagetex.py
del /s *.sagetex.sage
del /s *.sagetex.scmd
del /s *.sav
:del /s *.slf[0-9]*
del /s *.slg
del /s *.slo
del /s *.sls
:del /s *.slt[0-9]*
del /s *.snm
del /s *.soc
del /s *.sout
del /s *.spl
del /s *.sta
:del /s *.stc[0-9]*
del /s *.sympy
del /s *.synctex
del /s *.synctex.gz
del /s *.synctex.gz(busy)
del /s *.synctex(busy)
:del /s *.t[1-9]
:del /s *.t[1-9][0-9]
del /s *.table
del /s *.tdo
del /s *.tfm
del /s *.thm
del /s *.toc
del /s *.tps
del /s *.trc
del /s *.ttt
del /s *.upa
del /s *.upb
del /s *.ver
del /s *.vrb
del /s *.vtc
del /s *.wrt
del /s *.xcp
del /s *.xdv
del /s *.xdy
del /s *.xmpi
del /s *.xref
del /s *.xwm
del /s *.xyc
del /s *.xyd
:del /s *~[0-9]*
del /s acs-*.bib
del /s latex.out/
del /s pythontex-files-*/
del /s svg-inkscape/
del /s sympy-plots-for-*.tex/
del /s TSWLatexianTemp*
